# name: Build and Deploy to Docker Hub

# on:
#   push:
#     branches:
#       - master

# jobs:
#   build-and-push:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Check Out Repo
#       uses: actions/checkout@v2

#     - name: Log in to Docker Hub
#       uses: docker/login-action@v1
#       with:
#         username: ${{ secrets.DOCKERHUB_USERNAME }}
#         password: ${{ secrets.DOCKERHUB_PASSWORD }}

#     - name: Build and Push Docker image
#       uses: docker/build-push-action@v2
#       with:
#         context: .
#         file: ./Dockerfile
#         push: true
#         tags: chaitanyauniyal75658/mydocker_images:latest  # Replace with your Docker Hub username and repository

#     - name: Verify Pushed Image
#       run: docker pull chaitanyauniyal75658/mydocker_images:latest  # Replace with your Docker Hub username and repository
    
#     - name: Deploy to EC2
#       uses: appleboy/ssh-action@master
#       with:
#         host: ${{ secrets.SSH_HOST }}
#         username: ${{ secrets.SSH_USERNAME }}
#         key: ${{ secrets.SSH_KEY }}
#         script: |
#           sudo docker pull chaitanyauniyal75658/mydocker_images:latest
#           sudo docker stop web-app || true
#           sudo docker rm web-app || true
#           sudo docker run -d --name web-app -p 3000:5000 chaitanyauniyal75658/mydocker_images:latest




          # sudo docker pull chaitanyauniyal75658/mydocker_images:latest
          # sudo docker stop web-app || true
          # sudo docker rm web-app || true
          # sudo docker run -d --name web-app -p 3000:5000 chaitanyauniyal75658/mydocker_images:latest



name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: chaitanyauniyal75658/mydocker_images:latest

    - name: Verify Pushed Image
      run: docker pull chaitanyauniyal75658/mydocker_images:latest
    
    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          sudo docker pull chaitanyauniyal75658/mydocker_images:latest
          sudo docker stop web-app || true
          sudo docker rm web-app || true
          sudo docker run -d --name web-app -p 80:5000 \
            -e DATABASE_URL=${{ secrets.DATABASE_URL }} JWT_SECRET=${{ secrets.JWT_SECRET}} \
            chaitanyauniyal75658/mydocker_images:latest